### ISSUE TITLE
tabulate argument headers="firstrow" not set

### ISSUE THREAD

**Issue by jayvdb** [chfw/pyexcel-text#7]
tabulate has an argument `headers` which is not set when passing data containing a header row.

Tabulate could autodetect this in some cases (https://bitbucket.org/astanin/python-tabulate/issues/84/detect-headers-firstrow) , but pyexcel-text should be able to do this more reliably.

**Comment by chfw** [comment]
Have you teied to pass the headers to pyexcel?

**Comment by jayvdb** [comment]
I am doing a transcode from csv or xlsx to simple. No headers.

If I add headers="firstrow" in TextSheetWriter.write_array it works correctly for me, but im not 100% sure that is the correct solution.

**Comment by chfw** [comment]
```
>>> import pyexcel
>>> a=[["a","b"], [1,2]]
>>> s=pyexcel.Sheet(a)
>>> s
Sheet Name: pyexcel
+---+---+
| a | b |
+---+---+
| 1 | 2 |
+---+---+
>>> import pyexcel.ext.text
>>> s.save_as("test.html", headers="firstrow") # <-- This is what I intended:
```

**Comment by jayvdb** [comment]
That works correctly, and I can also workaround this using the highlevel `save_as`

``` bash
python3.4 -c 'import pyexcel, pyexcel.ext.text; pyexcel.save_as(file_name="test.xlsx", dest_file_name="test-out.simple", dest_headers="firstrow")'
```

However, the documented `mapdict` does not appear to be supported.

``` python
import pyexcel, pyexcel.ext.text
pyexcel.save_as(file_name="test.csv",
                dest_file_name="test-out.simple",
                dest_mapdict=["A", "B", "C"])'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/pyexcel-0.2.0-py3.4.egg/pyexcel/sources/__init__.py", line 318, in save_as
    sheet.save_to(dest_source)
  File "/usr/lib/python3.4/site-packages/pyexcel-0.2.0-py3.4.egg/pyexcel/sheets/sheet.py", line 20, in save_to
    source.write_data(self)
  File "/usr/lib/python3.4/site-packages/pyexcel-0.2.0-py3.4.egg/pyexcel/sources/file.py", line 80, in write_data
    **self.keywords)
  File "/usr/lib/python3.4/site-packages/pyexcel_io-0.1.0-py3.4.egg/pyexcel_io/__init__.py", line 296, in save_data
    **keywords)
  File "/usr/lib/python3.4/site-packages/pyexcel_io-0.1.0-py3.4.egg/pyexcel_io/__init__.py", line 260, in store_data
    writer.write(data)
  File "/usr/lib/python3.4/site-packages/pyexcel_io-0.1.0-py3.4.egg/pyexcel_io/base.py", line 290, in write
    sheet.write_array(sheet_dicts[name])
  File ".../pyexcel_text/__init__.py", line 119, in write_array
    **self.keywords))
TypeError: tabulate() got an unexpected keyword argument 'mapdict'
```

After playing around a little, it seems that the underlying problem is that -io's `SheetReader` has no concept of column headers unlike `NominableSheet`.

However if we upcast the csv sheet to a `NominableSheet`, `TextSheetWriter` can automatically detect the `NominableSheet` and set `headers` appropriately.  Patch coming soonish.

**Comment by chfw** [comment]
Quick epely: dest_mapdict was originally intended for database operations. So havent thought this use case

**Comment by jayvdb** [comment]
Patch is ready to roll, but I'll wait until after my other two pull requests have been reviewed.
